### PR TITLE
change package install order

### PR DESCRIPTION
**Pull request by mainguyenanhvu**
I found that we need to install ambertools first to prevent conflicting in conda environment. Please accept my pull request.

### CODE REVIEW

**Comment by egallicc** [comment]
Please explain the missing requirements error that you are observing. An Ambertools' dependency by AToM-OpenMM is news to me.

Ambertools is required to run the setup workflows. This could be achieved by installing Ambertools in the same or another environment as AToM-OpenMM.

**Comment by mainguyenanhvu** [comment]
I tried to use only one env to run different scripts in AToM-OpenMM. When I run [RBFE scripts](https://github.com/Gallicchio-Lab/AToM-OpenMM/tree/master/examples/RBFE/cdk2), it requires Ambertools. The commands I used in this situation are:
```
conda create -n atm -c conda-forge openmm-atmmetaforce-plugin configobj
conda activate atm
git clone https://github.com/Gallicchio-Lab/AToM-OpenMM.git
cd AToM-OpenMM
python setup.py install
conda install -c conda-forge ambertools
```

I installed Ambertools in the **atm** environment. It costs me a lot of time to solve the conflict. Therefore, I create a new environment, and install Ambertools before any other packages. It works efficiently. The commands I uses are:
```
conda create -n atm 
conda activate atm
conda install -c conda-forge ambertools
conda install -c conda-forge openmm
conda install -c conda-forge openmm-atmmetaforce-plugin
conda install -c conda-forge configobj
git clone https://github.com/Gallicchio-Lab/AToM-OpenMM.git
cd AToM-OpenMM
python setup.py install
```

**Comment by egallicc** [comment]
Okay, but please shorten the command as:
```
conda create -n atm -c conda-forge openmm-atmmetaforce-plugin configobj ambertools
```
and add a comment saying that `ambertools` is needed only for setting up the systems for some of the examples. Thanks

**Comment by mainguyenanhvu** [comment]
Thank you. The change was done.

**Pull request merged**
