### PR TITLE
improve definition of pos. restr. in structprep

### PR DESCRIPTION
**Pull request by smutao**
The implementation according to the suggestion in https://github.com/Gallicchio-Lab/AToM-OpenMM/pull/55#issuecomment-1813684858

### CODE REVIEW

**Comment by egallicc** [comment]
Thank you for this. I will test it as soon as possible.

**Comment by egallicc** [comment]
- please enclose the new code section that recognizes the solute within an if block based on the `restrain_solutes` boolean. Add  the `restrain_solutes = True` argument to `do_mintherm()`
- `massage_keywords()` does not need the `restrain_solutes` argument anymore
- please remove the lines that are commented out

thanks!

**Comment by egallicc** [comment]
The residue names of some of the ions added by Modeller() are not recognized. For example (see: [tip3p.xml](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/amber14/tip3p.xml)) the chloride ion is called 'CL', which is not included in the current list.
```
'CLA','NA+','K+','CL-','CA','MG'
```
Assuming OpenMM uses a consistent set of residue names for the ions for all water models, please add to the exclusion list above 'CL', 'NA', 'K', and 'F'.

Also, to avoid repetition, would it make sense to create a portable `residue_is_solvent()` function in `utils/AtomUtils.py` and use it in the `abfe` and `rbfe` versions of `structprep`? Something like:

In `utils.AtomUtils.py`:
```
def residue_is_solvent(res):
    ion_resnames = ['POT','SOD','CLA','NA+','K+','CL-','CL','CA','MG']
    wat_resnames = ['HOH','TIP3','WAT','TIP4','OPC','TIP5'] # sometimes we have 'TIP3V'
    if (res.name.upper() not in ion_resnames) and not (any(s in res.name for s in wat_resnames)):
        return True
    return False
```

And in `abfe/rbfe_structprep.py`:
```
from utils.AtomUtils import residue_is_solvent
if restrain_solutes:
    non_ion_wat_atoms = []
    for res in pdb.topology.residues():
        if residue_is_solvent(res):
           for atom in res.atoms():
                    non_ion_wat_atoms.append(atom.index)
```

**Comment by smutao** [comment]
thank you for the suggestions. please review the current modifications.

**Comment by egallicc** [comment]
Thank you for the excellent contribution.

**Pull request merged**
