### PR TITLE
V4.0.0rc-r1

### PR DESCRIPTION
**Pull request by smutao**
try to add:

1. use positional restraint for ligand(s) to replace the binding site-ligand CM-CM restraint while CM_KF is set to negative value;
2. allow ligands to be put ahead of protein via LIGAND_IN_BEGINNING keyword (by default is immediately after protein).

### CODE REVIEW

**Comment by egallicc** [comment]
- Please give the PR a meaningful name such as "define the binding site with ligand restraints"
- Submit a separate PR for each logically distinct change. The ordering of the ligand is unrelated to the binding site definition. It should be in a different PR

**Comment by egallicc** [comment]
Overloading the sign of the force constant for this purpose is confusing. A better strategy is to add the ligand atoms in question to POS_RESTRAINED_ATOMS. One would then want to use a different value of POSRE_FORCE_CONSTANT and POSRE_TOLERANCE for the receptor atoms than the ligand atoms. I propose the following changes that I think will be useful in other contexts as well.

- Generalize  POSRE_TOLERANCE and POSRE_FORCE_CONSTANT to arrays of force constants and tolerance that apply to each element of POS_RESTRAINED_ATOMS. For example, the 4th element of POSRE_FORCE_CONSTANT would be the force constant to apply to the 4th atom specified in POS_RESTRAINED_ATOMS.
- To implement the ligand restraints, add the ligand atoms to restrain to POS_RESTRAINED_ATOMS and indicate in POSRE_TOLERANCE and POSRE_FORCE_CONSTANT the values of the tolerance and force constant to use.

**Comment by smutao** [comment]
Dear Professor Gallicchio,

I agree with your suggestion. 

To change 'fc' and 'tol' into arrays, should I call 'atm_utils.addPosRestraints' function once for each restrained atom or add another 'addPosRestraints_2' function in the 'openmm-atmmetaforce-plugin' package?

**Comment by smutao** [comment]
The modification on `openmm-atmmetaforce-plugin` may take me some time. 

I personally like the idea of using `cntl` file because it offers more flexibility to tweak. Adding restraint information into OpenMM XML file is straightforward, but we may need to rebuild the XML file if we want to modify some restraint info. 

How about we add 4 more keywords to avoid the overloading? One switch keyword to ask whether or not to use ligand positional restraint, three keywords for ligand atom positional restraint.

**Comment by egallicc** [comment]
The point is that the software already supports positional restraints for an arbitrary set of atoms. We should take advantage and extend this facility rather than inventing a new one.

The other important consideration is that, eventually, most of the restraints introduced in ommsystem.py will be moved to the setup scripts and stored in the System before they are given to AToM proper. Try to implement the custom positional restraints function for the ligand that you are interested in into make_atm_system_from_rcpt_lig.py or make_atm_system_from_Amber.py. These scripts output the System XML file directly and AToM will automatically use the added restraints.

**Comment by smutao** [comment]
close for now.

**Pull request closed without merging**
