### PR TITLE
Use xtc to reduce trajectory volume and fix shebang.

### PR DESCRIPTION
**Pull request by 9527567**
OpenMM 8.1 has introduced the xtc reporter, perhaps we can reduce the trajectory volume through this?

### CODE REVIEW

**Comment by egallicc** [comment]
Thank you for this. Could you please submit changes unrelated to the XTC trajectory in separate PRs?

Also, a nice feature of the XTC format relative to DCD is its ability to store the timestamp of the saved frame. See  [XTCFile() ](http://docs.openmm.org/development/api-python/generated/openmm.app.xtcfile.XTCFile.html). Is there any way you could parse the TRJ_FREQUENCY keyword to set the `interval` argument of `XTCFile()`? It would be a huge help for synchronizing the information in the .out files with the frames in the trajectories in post-processing analysis.

**Comment by 9527567** [comment]
Okay, I will submit the modifications to the other parts in a separate PR.

**Comment by 9527567** [comment]
Can you handle this PR? If you have any questions, please let me know.

**Comment by egallicc** [comment]
Thank you. I will test it this weekend.

**Pull request merged**
